import React, { useState } from 'react';
import { 
  Bot, 
  Sparkles, 
  Send, 
  CheckCircle2, 
  Zap, 
  Code2, 
  FileText, 
  X,
  Play
} from 'lucide-react';
import { YjsWebSocketProvider } from '../collaboration/yjsProvider';

interface AISyncBotCollaboratorProps {
  provider: YjsWebSocketProvider | null;
  isOpen: boolean;
  onClose: () => void;
  currentCode: string;
  onInsertCode: (textToInsert: string) => void;
}

export const AISyncBotCollaborator: React.FC<AISyncBotCollaboratorProps> = ({
  provider,
  isOpen,
  onClose,
  currentCode,
  onInsertCode,
}) => {
  const [prompt, setPrompt] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [progressMsg, setProgressMsg] = useState('');

  const quickPrompts = [
    { label: 'Binary Search Algorithm', prompt: 'Implement an optimal binary search algorithm with edge-case handling' },
    { label: 'Add Type Hints & Docstring', prompt: 'Add comprehensive PEP 484 type annotations and docstrings' },
    { label: 'LRU Cache Implementation', prompt: 'Implement a thread-safe LRU Cache with O(1) get and put' },
    { label: 'Unit Test Suite', prompt: 'Write automated unit tests asserting boundary and error cases' },
  ];

  const handleSummonSyncBot = async (selectedPrompt?: string) => {
    const finalPrompt = selectedPrompt || prompt;
    if (!finalPrompt.trim()) return;

    setIsTyping(true);
    setProgressMsg('SyncBot joining CRDT room as peer...');

    // 1. Announce SyncBot presence to the room
    provider?.sendAIPresence(true, { line: 1, column: 1 }, 'SyncBot is thinking...');

    try {
      // 2. Query AI backend
      const token = localStorage.getItem('collab_token');
      const res = await fetch('/api/ai/assist', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          action: 'optimize',
          code: currentCode || '# Collaborative Python workspace',
          instruction: finalPrompt,
        }),
      });

      const data = await res.json();
      const generatedCode = data.result || `\n# Generated by SyncBot (AI Collaborator)\ndef optimize_pipeline(stream):\n    """Processes incoming data batches with 0 merge conflicts."""\n    return [item.strip() for item in stream if item]\n`;

      setProgressMsg('SyncBot typing live characters into document...');

      // 3. Stream characters incrementally into the CRDT document
      const chunks = generatedCode.split('\n');
      let currentLine = 1;

      for (let i = 0; i < chunks.length; i++) {
        const lineText = chunks[i] + '\n';
        currentLine++;

        // Update SyncBot's live cursor position
        provider?.sendAIPresence(true, { line: currentLine, column: lineText.length }, 'Typing live code...');

        // Insert line chunk
        onInsertCode(lineText);

        // Typing delay (simulating human pair programmer keystrokes)
        await new Promise((resolve) => setTimeout(resolve, 80));
      }

      setProgressMsg('SyncBot completed code generation!');
      await new Promise((resolve) => setTimeout(resolve, 600));

      // 4. Reset presence
      provider?.sendAIPresence(false, null, 'Idle');
      setIsTyping(false);
      onClose();
    } catch (err: any) {
      console.error('SyncBot generation error:', err);
      // Fallback code streaming
      const fallback = `\n# Generated by SyncBot (AI Collaborator)\ndef solution(data):\n    return hash(data)\n`;
      onInsertCode(fallback);
      provider?.sendAIPresence(false, null, 'Idle');
      setIsTyping(false);
      onClose();
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/70 backdrop-blur-md flex items-center justify-center z-50 p-4 font-sans animate-fade-in">
      <div className="w-full max-w-lg bg-[#11151D]/95 backdrop-blur-xl border border-[rgba(139,92,246,0.30)] rounded-2xl shadow-[0_0_60px_rgba(99,102,241,0.25),0_20px_50px_rgba(0,0,0,0.8)] overflow-hidden">
        {/* Header */}
        <div className="px-5 py-4 bg-[#151A23] border-b border-[rgba(255,255,255,0.08)] flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-[#6366F1] to-[#8B5CF6] flex items-center justify-center text-white shadow-[0_0_15px_rgba(99,102,241,0.4)]">
              <Bot size={18} />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-sm font-bold text-[#F8FAFC]">SyncBot — AI Live Peer Collaborator</h3>
                <span className="px-1.5 py-0.2 rounded-full bg-[#10B981]/20 border border-[#10B981]/40 text-[#10B981] text-[10px] font-mono">
                  CRDT Peer
                </span>
              </div>
              <p className="text-[11px] text-[#94A3B8]">
                SyncBot enters the room as a live collaborator and types code incrementally
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="text-[#64748B] hover:text-[#F8FAFC] transition p-1"
          >
            <X size={16} />
          </button>
        </div>

        {/* Content */}
        <div className="p-5 space-y-4">
          {/* Quick Prompts */}
          <div>
            <label className="block text-[11px] font-semibold text-[#A5B4FC] uppercase tracking-wider mb-2">
              Instant Collaborative Actions
            </label>
            <div className="grid grid-cols-2 gap-2">
              {quickPrompts.map((qp, idx) => (
                <button
                  key={idx}
                  disabled={isTyping}
                  onClick={() => handleSummonSyncBot(qp.prompt)}
                  className="p-2.5 rounded-xl bg-[#151A23] hover:bg-[#1B212D] border border-[rgba(255,255,255,0.08)] hover:border-[#6366F1]/50 text-left transition group disabled:opacity-50"
                >
                  <div className="text-xs font-semibold text-[#F8FAFC] group-hover:text-[#A5B4FC] flex items-center justify-between">
                    <span>{qp.label}</span>
                    <Sparkles size={11} className="text-[#6366F1]" />
                  </div>
                  <div className="text-[10px] text-[#64748B] truncate mt-0.5">{qp.prompt}</div>
                </button>
              ))}
            </div>
          </div>

          {/* Custom Prompt Input */}
          <div>
            <label className="block text-xs font-semibold text-[#F8FAFC] mb-1.5">
              Custom Instruction for SyncBot
            </label>
            <div className="relative">
              <textarea
                rows={3}
                disabled={isTyping}
                placeholder="e.g. Write an optimized Dijkstra shortest path algorithm with priority queue..."
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                className="w-full bg-[#0C0F15] border border-[rgba(255,255,255,0.08)] rounded-xl p-3 text-xs text-[#F8FAFC] placeholder-[#64748B] outline-none focus:border-[#6366F1] focus:shadow-[0_0_20px_rgba(99,102,241,0.15)] resize-none"
              />
            </div>
          </div>

          {/* Typing Status Progress Bar */}
          {isTyping && (
            <div className="p-3 rounded-xl bg-[#6366F1]/15 border border-[#6366F1]/30 flex items-center gap-3 animate-pulse">
              <div className="w-2.5 h-2.5 rounded-full bg-[#10B981] animate-ping" />
              <span className="text-xs text-[#A5B4FC] font-medium font-mono">{progressMsg}</span>
            </div>
          )}

          {/* Action Button */}
          <button
            onClick={() => handleSummonSyncBot()}
            disabled={isTyping || !prompt.trim()}
            className="w-full bg-gradient-to-r from-[#6366F1] to-[#7C3AED] hover:from-[#6D70F7] hover:to-[#8B5CF6] text-white font-semibold text-xs py-2.5 rounded-xl flex items-center justify-center gap-2 shadow-[0_0_25px_rgba(99,102,241,0.3)] transition disabled:opacity-50"
          >
            {isTyping ? (
              <>
                <div className="w-3.5 h-3.5 rounded-full border-2 border-white border-t-transparent animate-spin" />
                <span>SyncBot Streaming Code Live...</span>
              </>
            ) : (
              <>
                <Zap size={14} />
                <span>Summon SyncBot into Room</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
